// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4dugkRnmlxlfhaHFul16NE8HcmEk0ryE',
    appId: '1:158954104977:web:94b9b75cc57b20f5173730',
    messagingSenderId: '158954104977',
    projectId: 'liguapptest',
    authDomain: 'liguapptest.firebaseapp.com',
    storageBucket: 'liguapptest.appspot.com',
    measurementId: 'G-W3WEKXC2QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJa70kc-27ORrQUaM2PS-a0Tga7NeDgmA',
    appId: '1:158954104977:android:6faa9c884a01f9a2173730',
    messagingSenderId: '158954104977',
    projectId: 'liguapptest',
    storageBucket: 'liguapptest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWBfMWPSIc2Xdhxgry4ykewpMAb16hk6k',
    appId: '1:158954104977:ios:aed592a103826b42173730',
    messagingSenderId: '158954104977',
    projectId: 'liguapptest',
    storageBucket: 'liguapptest.appspot.com',
    iosBundleId: 'com.lingualink.linguapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWBfMWPSIc2Xdhxgry4ykewpMAb16hk6k',
    appId: '1:158954104977:ios:0cbe378f19fdf233173730',
    messagingSenderId: '158954104977',
    projectId: 'liguapptest',
    storageBucket: 'liguapptest.appspot.com',
    iosBundleId: 'com.lingualink.linguapp.RunnerTests',
  );
}
